---
- name: Install my favorite CLI tools
  hosts: "*"

  become: true
  tasks:
  - name: Update list of packages
    community.general.pacman:
      update_cache: true

  - name: Remove 'nano'
    community.general.pacman:
      name: nano
      state: absent

  - name: Remove 'vim'
    community.general.pacman:
      name:
        - vim
        - vim-runtime
      state: absent

  - name: Install 'midnight Commander'
    community.general.pacman:
      name: mc
      state: present

  - name: Install 'tmux'
    community.general.pacman:
      name: tmux
      state: present

  - name: Install 'curl'
    community.general.pacman:
      name: curl
      state: present

  - name: Install 'wget'
    community.general.pacman:
      name: wget
      state: present

  - name: Install 'htop'
    community.general.pacman:
      name: htop
      state: present

  - name: Install 'bmon'
    community.general.pacman:
      name: bmon
      state: present

  - name: Install 'git'
    community.general.pacman:
      name: git
      state: present

  - name: Install 'zsh'
    community.general.pacman:
      name: zsh
      state: present

  - name: Install 'neovim'
    community.general.pacman:
      name: neovim
      state: present

  - name: Install 'exa' replacement for 'ls'
    community.general.pacman:
      name: exa
      state: present

  - name: Install 'bat' replacement for 'cat'
    community.general.pacman:
      name: bat
      state: present

  - name: Install 'neofetch' because I'm using Arch
    community.general.pacman:
      name: neofetch
      state: present

  - name: Install 'pkgfile'
    community.general.pacman:
      name: pkgfile
      state: present

  - name: Install 'mlocate'
    community.general.pacman:
      name: mlocate
      state: present

  - name: Install 'flatpak'
    community.general.pacman:
      name: flatpak
      state: present
