---
- name: Update pacman's mirrorlist  
  hosts: "*"

  tasks:
  - name: Install pacman-contrib for 'rankmirrors'
    community.general.pacman:
      name: pacman-contrib
      state: present
    become: true
  
  - name: Download and rank mirrors
    ansible.builtin.command:
      cmd: bash -c "curl -s 'https://archlinux.org/mirrorlist/?country=US&protocol=https&use_mirror_status=on' | sed -e 's/^#Server/Server/' -e '/^#/d' | rankmirrors -n 5 - > /etc/pacman.d/mirrorlist"
    become: true
    changed_when: true
