---
- name: Installing Zsh and dependencies
  hosts: "*"

  tasks:
    - name: Update list of packages
      become: true
      community.general.pacman:
        update_cache: true
      
    - name: Install 'zsh'
      become: true
      community.general.pacman:
        name: extra/zsh
        state: present

    - name: Install 'git'
      become: true
      community.general.pacman:
        name: extra/git
        state: present

    - name: Install 'tmux'
      become: true
      community.general.pacman:
        name: community/tmux
        state: present

    - name: Install 'fzf'
      become: true
      community.general.pacman:
        name: community/fzf
        state: present

    - name: Install 'aur/antibody-bin'
      kewlfft.aur.aur:
        name: aur/antibody-bin
        use: trizen
        state: present
      become: true
      become_user: pkg
      
    - name: Install 'aur/find-the-command'
      kewlfft.aur.aur:
        name: aur/find-the-command
        use: trizen
        state: present
      become: true
      become_user: pkg
    
    - name: Remove old '.zshrc' if exists
      ansible.builtin.file:
        state: absent
        path: ~/.zshrc

    - name: Create '.zshrc' for user
      ansible.builtin.blockinfile:
        path: ~/.zshrc
        mode: 0644
        create: true
        state: present
        block: |
          #zmodload zsh/zprof
          
          setopt autocd
          # beep extendedglob nomatch
          bindkey -v
          
          # Find-The-Command
          source /usr/share/doc/find-the-command/ftc.zsh
          
          
          #---------------------------------------------#
          #                 antibody
          #---------------------------------------------#
          source <(antibody init)
          antibody bundle << EOF
          # todo: see https://github.com/caarlos0/dotfiles/antibody/bundles.txt
          
          mafredri/zsh-async
          # robbyrussell/oh-my-zsh path:plugins/git
          zsh-users/zsh-completions
          zsh-users/zsh-autosuggestions
          #zsh-users/zsh-syntax-highlighting
          zdharma/fast-syntax-highlighting
          zsh-users/zsh-history-substring-search
          
          ####  prompt  ####
          #sindresorhus/pure
          #dfurnes/purer
          #aldn/purer
          
          #nojhan/liquidprompt
          
          EOF
          
          #---------------------------------------------#
          #                 history
          #---------------------------------------------#
          HISTFILE=~/.histfile
          HISTSIZE=5000
          SAVEHIST=5000
          
          bindkey '^R' history-incremental-search-backward
          
          #---------------------------------------------#
          #                 completion
          #---------------------------------------------#
          #zstyle ':completion:*' menu select
          zstyle ':completion:*' rehash true
          zstyle ':completion:*' completer _complete
          zstyle ':completion:*' matcher-list '' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' '+l:|=* r:|=*'
          autoload -Uz compinit; compinit
          
          # zstyle ':completion::complete:*' gain-privileges 1
          setopt COMPLETE_ALIASES
          
          autoload -Uz up-line-or-beginning-search down-line-or-beginning-search
          zle -N up-line-or-beginning-search
          zle -N down-line-or-beginning-search
          [[ -n "$key[Up]"   ]] && bindkey -- "$key[Up]"   up-line-or-beginning-search
          [[ -n "$key[Down]" ]] && bindkey -- "$key[Down]" down-line-or-beginning-search
          bindkey "^[[1;5D" backward-word
          bindkey "^[[1;5C" forward-word
          
          #---------------------------------------------#
          #                 prompt
          #---------------------------------------------#
          #PURE_PROMPT_SYMBOL_COLOR="cyan"
          #PURE_CMD_MAX_EXEC_TIME=10
          #zstyle :prompt:pure:path color white
          #zstyle :prompt:pure:prompt:success color cyan
          #zstyle :prompt:pure:prompt:error color cyan
          
          
          autoload -Uz promptinit; promptinit
          prompt walters
          
          
          
          #---------------------------------------------#
          #                 extra conf
          #---------------------------------------------#
          #source_env_file() {
          #    [[ -e ~/.cfg/env/$1 ]] && emulate sh -c 'source ~/.cfg/env/$1'
          #}
          
          # source_env_file vars
          #source_env_file aliases
          #source_env_file subs
          
          #---------------------------------------------#
          #                 aliases
          #---------------------------------------------#
          alias cp='cp -i'                          # confirm before overwriting something
          alias rm='rm -i'
          alias df='df -h'                          # human-readable sizes
          alias free='free -m'                      # show sizes in MB
          alias ls=exa
          alias ls='exa --color=auto'
          alias ll='exa -alF'
          alias la='exa -A'
          alias l='exa -CF'
          alias cat=bat
          alias grep='grep --color=auto'
          alias fgrep='fgrep --color=auto'
          alias egrep='egrep --color=auto'
          alias diff='diff --color=auto'
          alias more='less'
          alias vim=nvim
          alias e=nvim
          alias bc='bc -q'
          alias ps-total-mem="ps aux --sort rss | awk '{sum += \$6} END {print sum}'"
          alias clean-journal='journalctl --vacuum-time=2weeks'
          alias pac-up='sudo pacman -Syu'
          alias pac-list-explicits='pacman -Qet'
          alias pac-list-orphans='pacman -Qdt'
          alias pac-remove-orphans='sudo pacman -Rns $(pacman -Qtdq)'
          alias aur=trizen
          alias aur-up='aur -Syu --noconfirm'
          
          
          
          #---------------------------------------------#
          #             wayland env vars
          #---------------------------------------------#
          #export GDK_SCALE=$dpi_scale
          #export QT_SCALE_FACTOR=$dpi_scale
          #export GDK_BACKEND=wayland
          #export QT_QPA_PLATFORM=wayland
          #export QT_QPA_PLATFORMTHEME=gtk2
          #export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
          #export SDL_VIDEODRIVER=wayland
          export MOZ_ENABLE_WAYLAND=1
          
          # Repaint screen upon exiting less
          #export LESS=R
          #export GREP_COLOR='1;32'
          export FZF_DEFAULT_COMMAND='ag --hidden --depth=10 --ignore .git -f -g ""'
          export MAKEFLAGS="-j$(grep processor /proc/cpuinfo|wc -l)"
          export EDITOR=vim
          export PATH=$HOME/.local/bin:$PATH
          export PATH=$HOME/.nimble/bin:$PATH
          
          #---------------------------------------------#
          #                 functions
          #---------------------------------------------#
          set-title()
          {
            printf "\e]2;$1\a"
          }

    - name: Get the 'username'
      ansible.builtin.shell:
        cmd: whoami
      changed_when: false
      register: running_as

    - name: Set 'zsh' for '{{ running_as.stdout }}'.
      become: true
      ansible.builtin.user:
        name: "{{ running_as.stdout }}" 
        shell: /usr/bin/zsh
      when: running_as.rc == 0
