---

# NOTE:
# .zshrc will be installed by dotfiles.yml playbook as part of dotfiles
#


- name: Installing Zsh and dependencies
  hosts: "*"

  tasks:
    - name: Update list of packages
      become: true
      community.general.pacman:
        update_cache: true
      
    - name: Install 'zsh'
      become: true
      community.general.pacman:
        name: extra/zsh
        state: present

    - name: Install 'git'
      become: true
      community.general.pacman:
        name: extra/git
        state: present

    - name: Install 'tmux'
      become: true
      community.general.pacman:
        name: community/tmux
        state: present

    - name: Install 'fzf'
      become: true
      community.general.pacman:
        name: community/fzf
        state: present

    - name: Install 'aur/antibody-bin'
      kewlfft.aur.aur:
        name: aur/antibody-bin
        use: trizen
        state: present
      become: true
      become_user: pkg
      
    - name: Install 'aur/find-the-command'
      kewlfft.aur.aur:
        name: aur/find-the-command
        use: trizen
        state: present
      become: true
      become_user: pkg

    - name: Get the 'username'
      ansible.builtin.shell:
        cmd: whoami
      changed_when: false
      register: running_as

    - name: Set 'zsh' for '{{ running_as.stdout }}'.
      become: true
      ansible.builtin.user:
        name: "{{ running_as.stdout }}" 
        shell: /usr/bin/zsh
      when: running_as.rc == 0
